services:
  - name: bundleService
    url: http://docker.for.mac.localhost:9090/bundle-provider
    credentials:
      oauth2:
        token_url: https://dev-vmfs2xsxy47w5vfr.us.auth0.com/oauth/token
        grant_type: client_credentials
        client_id: g72K0rwxakxiS44Nt1kISMooPHWLnjFu
        client_secret: F9-9n_junRqg0fJX7zSrs9iM4oW2a1rcNXb23JSahLEvfiBgHA_Dkbjg6DzSut37
        additional_parameters:
          audience: https://dev-vmfs2xsxy47w5vfr.us.auth0.com/api/v2/

bundles:
  authz:
    service: bundleService
    resource: download/policies.tar.gz
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

