services:
  - name: bundleService
    url: http://docker.for.mac.localhost:9090/bundle-provider
    credentials:
      bearer:
        token: "bearer-token-test-210461c6-b22c-419c-a3d1-56ea5744d591"
bundles:
  authz:
    service: bundleService
    resource: download/policies.tar.gz
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

